package sg.ntu.dataminers.singbiker;

public interface IntentConstants {
    int CONSTANT_INT_ROUTEPLOTACTIVITY = 1001;
    int CONSTANT_INT_INDIVIDUALROUTEACTIVITY = 1002;
    int CONSTANT_INT_TRIPACTIVITY = 1003;
    int CONSTANT_INT_INDIVIDUALTRIPACTIVITY = 1004;
    int CONSTANT_INT_HISTORYLISTACTIVITY = 1005;
    int CONSTANT_INT_SETTINGACTIVITY = 1006;
    int CONSTANT_INT_HAZEACTIVITY = 1007;

    String CONSTANT_STRING_CALLINGACTIVITY = "callingActivity";
    String CONSTANT_STRING_TRIP = "trip";
    String CONSTANT_STRING_ROUTE = "route";
    String CONSTANT_STRING_ROUTELIST = "routeList";
}
